# Generated by Django 3.1.4 on 2021-02-18 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200, null=True)),
                ('about_shortDes', models.TextField(null=True)),
                ('about_detail', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('user_contact', models.CharField(max_length=120)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_desc', models.TextField()),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_location', models.CharField(max_length=120)),
                ('event_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_name', models.CharField(max_length=200)),
                ('ex_image', models.ImageField(null=True, upload_to='images/')),
                ('ex_designation', models.CharField(blank=True, max_length=120, null=True)),
                ('ex_detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gellery_title', models.CharField(blank=True, max_length=120, null=True)),
                ('gellery_image', models.ImageField(upload_to='images/')),
                ('gellery_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='')),
                ('gellery_detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_name', models.CharField(max_length=120)),
                ('mem_image', models.ImageField(null=True, upload_to='images/')),
                ('mem_details', models.TextField(blank=True, null=True)),
                ('mem_joinDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('mem_contact', models.CharField(max_length=200, null=True)),
                ('mem_email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_image', models.ImageField(null=True, upload_to='images/')),
                ('pro_detail', models.TextField(null=True)),
                ('pro_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=200)),
                ('story_image', models.ImageField(upload_to='images/')),
                ('story_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_title', models.CharField(max_length=200)),
                ('term_desc', models.TextField()),
            ],
        ),
    ]
