# Generated by Django 3.1.4 on 2021-02-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='mem_address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
