# Generated by Django 3.1.4 on 2021-02-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityApp', '0003_auto_20210218_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(),
        ),
    ]
