# Generated by Django 3.1.4 on 2021-02-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityApp', '0004_auto_20210222_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('event_name',)},
        ),
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterIndexTogether(
            name='events',
            index_together={('id', 'slug')},
        ),
    ]
