# Generated by Django 3.1.4 on 2021-02-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityApp', '0005_auto_20210222_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gellery_title', models.CharField(blank=True, max_length=120, null=True)),
                ('gellery_image', models.ImageField(upload_to='images/')),
                ('gellery_detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=200, null=True)),
                ('video_gallery', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
